version: "3.11"

services:
  social_network:
    build: .
    volumes:
      - .:/social_network
    ports:
      - 8080:8080
    env_file:
      - .env
    command: >
      sh -c "python manage.py makemigrations \
      && python manage.py migrate \
      && python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - social_network_db

  social_network_db:
      image: postgres:14.6-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
      ports:
        - 5432:5432
      expose:
        - 5432

volumes:
  postgres_data: