version: "3.11"

services:
  social_network:
    build: .
    volumes:
      - .:/social_network
    ports:
      - 8080:8080
    env_file:
      - .env
    command: >
      sh -c "python manage.py makemigrations \
      && python manage.py migrate \
      && python manage.py runserver 0.0.0.0:8080"
